import { ThemeColors, ThemeName, Language } from '../types';

export const THEMES: Record<ThemeName, ThemeColors> = {
  light: { 
    bg: '#F0EEE9', card: '#E7EAEE', textMain: '#2B2B6E', textSub: '#7D8090', border: '#AEB4C1', 
    main: '#2B2B6E', textBrand: '#2B2B6E', sub: '#918A9E', positive: '#70ca16', negative: '#c0397b', accent: '#ded717', blue: '#8036c9'      
  },
  slightGray: { 
    bg: '#E0DED8', card: '#F5F4F2', textMain: '#1A1A1A', textSub: '#444444', border: '#B5B5B5', 
    main: '#1495CC', textBrand: '#0D76A1', sub: '#A9A30A', positive: '#41C37C', negative: '#C01B84', accent: '#E6AC5B', blue: '#4F7BB5' 
  },
  dark: { 
    bg: '#DEE6E1', card: '#FCFCFC', textMain: '#262216', textSub: '#668177', border: '#BFC6B2', 
    main: '#45CDA2', textBrand: '#1A8F70', sub: '#668177', positive: '#45CDA2', negative: '#FF5C5C', accent: '#FFC44D', blue: '#45CDA2' 
  },
  extraDark: {
    bg: '#050505', card: '#101010', textMain: '#FFFFFF', textSub: '#D0D0D0', border: '#555555',
    main: '#37B3AA', textBrand: '#37B3AA', sub: '#79D3C9', positive: '#4FDC8A', negative: '#FF7070', accent: '#FFD166', blue: '#37B3AA'
  },
  creative: {
    bg: '#FAFAFA', card: '#FFFFFF', textMain: '#333333', textSub: '#666666', border: '#E5E7EB',
    main: '#8B5CF6', textBrand: '#7C3AED', sub: '#EC4899', positive: '#10B981', negative: '#EF4444', accent: '#F59E0B', blue: '#6366F1'
  }
};

export const TEXT = {
  en: {
    title: "Project Dashboard", subtitle: "Annual Assessment System",
    dataSource: "Data Source", import: "Load Excel / CSV",
    owner: "Owner", status: "Status", category: "Category", cluster: "Cluster", month: "Period (Month)",
    total: "Total Items", totalDesc: "All Projects Loaded",
    completed: "Completed", completedDesc: "Status: 'Closed'",
    onTime: "On-Time Rate", onTimeDesc: "Due Date == Revision_1",
    statusDist: "Status Distribution", statusSub: "Overview by status",
    catAnalysis: "Category Analysis", catSub: "Breakdown by category/cluster",
    ownerCont: "Owner Contribution", ownerSub: "Project volume by owner",
    gantt: "Project Schedule (Gantt)", ganttSub: "Timeline with Independent Filters",
    evidence: "Evidence List", feedback: "Feedback", save: "Save",
    thHighlights: "Highlights & Deliverables", thDesc: "Description", thProgress: "Progress",
    wizBtn: "Wiz", wizTitle: "Wiz Summary", wizSub: "Insights based on current Gantt view",
    wizAvgLoad: "MH Load / Workday", wizProjects: "Active Projects", wizOwners: "Owners Involved", wizDeliv: "Project & Key Deliverables",
    wizWorkload: "Resource Allocation (Daily MH/d)", wizMaxCap: "Max Capacity: 5.0 MH/d",
    wizViewProj: "By Project", wizViewCat: "Category-Cluster", wizViewWeekly: "Weekly Highlight",
    wizViewMh: "Hours Review",
    wizMhProjectTitle: "Workload Highlight Summary",
    wizMhClusterTitle: "Summary by Category",
    wizMhBriefTitle: "4-Point Diagnostic Metrics",
    btnExportHtml: "HTML Report",
    tipExportHtml: "Generate a standalone HTML page for this summary.",
    lblViewCluster: "By Cluster", lblViewProject: "By Project", 
    wizFilterProc: "Processing", wizFilterPend: "Pending", wizFilterClosed: "Closed", wizFilterAll: "All Status", 
    wizChartEmptyStatus: "No tasks found for the selected status in this period.",
    wizNoDeliv: "No specific deliverable. Please update manually...",
    wizAvgTooltipFormula: "💡 Formula: Total MH ÷ Active Days",
    wizAvgTooltipDesc: "Calculates the macro-level daily bandwidth required across the actual timespan of all 'Processing' projects.",
    wizAvgTooltipExTitle: "Example:",
    wizAvgTooltipEx1: "3 overlapping projects require 35 Total MH.",
    wizAvgTooltipEx2: "Projects span across a 14-day window.",
    wizAvgTooltipEx3: "Result: 35 ÷ 14 = <span style='font-weight:bold; color:#FFFFFF;'>2.5 MH/d</span>.",
    wizMaxCapTooltipTitle: "Why cap at 5.0 hours instead of 8.0?",
    wizMaxCapTooltipDesc1: "Planning and strategic work are not purely administrative. Colleagues are expected to consciously engage in preliminary planning, pilot deployments, and iterative trial-and-error before delivering final results. This requires dedicated buffer time.",
    wizMaxCapTooltipDesc2: "Furthermore, reserving time fragments encourages self-directed learning and the ideation of innovative proposals.",
    tooltipTopProj: "--- Top 5 Projects ---", tooltipMore: "more",
    tipCount: "Counts the absolute number of distinct projects matching the criteria.",
    tipMH: "Calculates Accumulated Working Hours: Sum of (Daily MH × Duration).",
    tipCat: "Groups the project data by standard Category.",
    tipClust: "Groups the project data by organizational Cluster.",
    tipStatusDist: "Switches the chart data source across Status, Category, or Cluster.",
    tipWizViewProj: "Lists all individual projects.",
    tipWizViewCat: "Hierarchically groups projects by Category and Cluster.",
    tipWizViewWeekly: "Filters to show only projects active in the current calendar week.",
    tipWizViewMh: "Analyze accumulated man-hours distributed by individual projects and categories.",
    tipViewCluster: "Aggregates Daily MH of all overlapping projects within the same Cluster on a given day.",
    tipViewProject: "Displays the Daily MH for each individual project independently on a given day.",
    tipStatusFilter: "Filters the workload calculation by specific project statuses.",
    lblModalTitle: "Customize Theme Colors", lblModalSub: "Adjust HEX codes. Charts will automatically adapt to these settings.",
    lblBgGroup: "Backgrounds & Borders", lblTextGroup: "Typography", lblBrandGroup: "Brand & Chart Palette", lblStatusGroup: "Status Indication",
    lblBgPage: "Page Background", descBgPage: "Applies to the main body and canvas areas.",
    lblBgCard: "Card Background", descBgCard: "Applies to dashboard panels, modals, and input fields.",
    lblBgBorder: "Border Color", descBgBorder: "Applies to card borders, table dividers, and chart grids.",
    lblTxtMain: "Main Text", descTxtMain: "Primary color for titles, values, and table data.",
    lblTxtSub: "Sub/Label Text", descTxtSub: "Secondary color for subtitles, labels, and table headers.",
    lblTxtBlue: "Link/Highlight Text", descTxtBlue: "Color for active states and 'In Progress' text badges.",
    lblBrandMain: "Chart Base (Brand Main)", descBrandMain: "Primary color for all bar charts, headers, and 'Processing' tasks.",
    lblBrandSub: "Chart Color 2 (Brand Sub)", descBrandSub: "Secondary color for stacked bar charts, badges, and structural highlights.",
    lblBrandAccent: "Chart Color 3 (Accent/Gold)", descBrandAccent: "Applies to stacked charts, the 'TODAY' indicator, and 'Wiz' button.",
    lblStatusPos: "Positive (Green)", descStatusPos: "Applies to 'Completed' metrics and 'Closed' chart elements.",
    lblStatusNeg: "Negative (Red)", descStatusNeg: "Applies to the 5.0 Capacity warning line and 'Pending' status.",
    lblBtnCancel: "Cancel", lblBtnApply: "Apply & Refresh", lblBtnExportMd: "Export Markdown",
    wizDiagContextTitle: "Context (Capacity Allocation)",
    wizDiagScheduleTitle: "Schedule (Timeline Tracking)",
    wizDiagQualityTitle: "Quality (Data Integrity)",
    wizDiagHighlightTitle: "Highlight (Risk & Support)",
    wizDiagScheduleGood: "All active projects are on track. Excellent!",
    wizDiagScheduleBad: "The following projects are delayed/overdue: ",
    wizDiagQualityGood: "All projects have concrete deliverables and progress. Great job!",
    wizDiagQualityBad: "The following projects lack concrete deliverables or progress updates: ",
    wizDiagHighlightGood: "No abnormal risks or support requests detected.",
    wizDiagHighlightBad: "Attention required! The following projects have flagged risks, issues, or support needs: "
  },
  zh: {
    title: "專案儀表板", subtitle: "年度考核系統 (Annual Assessment)",
    dataSource: "資料來源", import: "匯入 Excel / CSV",
    owner: "負責人", status: "狀態", category: "類別", cluster: "群組", month: "期間 (月份)",
    total: "總項目數", totalDesc: "已載入所有專案",
    completed: "已結案", completedDesc: "狀態為 'Closed'",
    onTime: "準時達成率", onTimeDesc: "原始到期日 == 修訂版 1",
    statusDist: "狀態分佈", statusSub: "整體狀態概覽",
    catAnalysis: "類別分析", catSub: "依類別/群組細分",
    ownerCont: "負責人貢獻度", ownerSub: "依負責人統計案件量",
    gantt: "專案時程 (Gantt)", ganttSub: "獨立篩選時間軸",
    evidence: "證據清單", feedback: "回饋與建議", save: "儲存",
    thHighlights: "重點與交付物", thDesc: "描述", thProgress: "進度",
    wizBtn: "Wiz 助手", wizTitle: "Wiz 智慧摘要", wizSub: "基於目前甘特圖視角的洞察",
    wizAvgLoad: "工時負載/工作日", wizProjects: "活躍專案", wizOwners: "參與負責人", wizDeliv: "專案描述與關鍵交付物",
    wizWorkload: "資源負載分佈 (每日工時)", wizMaxCap: "最大法定產能: 5.0 MH/d",
    wizViewProj: "依專案", wizViewCat: "類別-群組", wizViewWeekly: "週報亮點",
    wizViewMh: "工時審查",
    wizMhProjectTitle: "工作負載亮點 (專案排行)",
    wizMhClusterTitle: "類別貢獻摘要 (Category)",
    wizMhBriefTitle: "四大結構化診斷指標",
    btnExportHtml: "HTML 報告",
    tipExportHtml: "將此專案摘要匯出為獨立的診斷 HTML 網頁報告。",
    lblViewCluster: "依群組", lblViewProject: "依專案", 
    wizFilterProc: "執行中", wizFilterPend: "待處理", wizFilterClosed: "已結案", wizFilterAll: "全部狀態", 
    wizChartEmptyStatus: "此期間無符合所選狀態的任務可計算產能。",
    wizNoDeliv: "無具體交付物，請手動填寫更新...",
    wizAvgTooltipFormula: "💡 公式：總投入工時 ÷ 總活躍天數",
    wizAvgTooltipDesc: "計算篩選區間內，所有「執行中 (Processing)」專案在實際時間跨度下的宏觀每日資源消耗率。",
    wizAvgTooltipExTitle: "範例：",
    wizAvgTooltipEx1: "3個疊加專案共需投入 35 小時。",
    wizAvgTooltipEx2: "專案分散於 14 天的週期內。",
    wizAvgTooltipEx3: "結果：35 ÷ 14 = <span style='font-weight:bold; color:#FFFFFF;'>2.5 MH/d</span>。",
    wizMaxCapTooltipTitle: "為何設定 5 個小時而非 8 小時？",
    wizMaxCapTooltipDesc1: "因為，企劃部工作並非全然事務性質，期望同仁有意識地進行前期規劃，試行部署，試錯迭代後提出成果，因此需要額外的留白時段。",
    wizMaxCapTooltipDesc2: "此外，預留時間片段，也鼓勵同仁自主學習與發想新案。",
    tooltipTopProj: "--- 前五大耗能專案 ---", tooltipMore: "項",
    tipCount: "計算符合條件的不重複專案絕對數量。",
    tipMH: "計算累積投入工時：加總 (每日工時 × 執行天數)。",
    tipCat: "依據標準專案類別進行分群。",
    tipClust: "依據組織群組進行分群。",
    tipStatusDist: "切換圓餅圖的資料來源：狀態、類別或群組。",
    tipWizViewProj: "獨立表列每一個專案。",
    tipWizViewCat: "依據類別與群組的階層關係來歸納專案。",
    tipWizViewWeekly: "僅篩選出當前日曆週內活躍的專案。",
    tipWizViewMh: "分析個別專案與類別策略所分配的累計總投入工時佔比。",
    tipViewCluster: "將同一群組內所有重疊專案的每日工時，依日期加總計算。",
    tipViewProject: "獨立顯示每個專案在特定日期的每日工時消耗。",
    tipStatusFilter: "依據特定的專案狀態來過濾產能負載計算。",
    lblModalTitle: "自定義主題色彩", lblModalSub: "調整色碼 (HEX)，所有圖表與介面將自動即時套用設定。",
    lblBgGroup: "背景與邊框", lblTextGroup: "文字排版", lblBrandGroup: "品牌與圖表調色盤", lblStatusGroup: "狀態指示",
    lblBgPage: "頁面背景 (Page Background)", descBgPage: "應用於主要背景、網頁空白處。",
    lblBgCard: "卡片背景 (Card Background)", descBgCard: "應用於儀表板卡片、彈出視窗、輸入框。",
    lblBgBorder: "邊框顏色 (Border Color)", descBgBorder: "應用於卡片邊框、圖表格線、表格分隔線。",
    lblTxtMain: "主文字 (Main Text)", descTxtMain: "應用於大標題、KPI 數值、表格主資料。",
    lblTxtSub: "副文字 (Sub/Label Text)", descTxtSub: "應用於副標題、圖表標籤、表格標題。",
    lblTxtBlue: "強調文字 (Link/Highlight Text)", descTxtBlue: "應用於觸發狀態、特定的標籤與「執行中」狀態。",
    lblBrandMain: "圖表主色 (Chart Base / Brand Main)", descBrandMain: "應用於所有長條圖的基底色、主視覺邊框與「執行中」任務。",
    lblBrandSub: "圖表次色 (Chart Color 2 / Brand Sub)", descBrandSub: "應用於堆疊長條圖的循環配色、次視覺邊框與進階標籤。",
    lblBrandAccent: "圖表強調色 (Chart Color 3 / Accent)", descBrandAccent: "應用於堆疊長條圖配色、「TODAY」發光線與 Wiz 按鈕。",
    lblStatusPos: "正面狀態 (Positive / Green)", descStatusPos: "應用於「已結案」數據、準時率、「Closed」狀態。",
    lblStatusNeg: "負面狀態 (Negative / Red)", descStatusNeg: "應用於 5.0 警戒線、延遲數據、「Pending」狀態。",
    lblBtnCancel: "取消", lblBtnApply: "套用並重新整理", lblBtnExportMd: "匯出 Markdown",
    wizDiagContextTitle: "Context (產能配置)",
    wizDiagScheduleTitle: "Schedule (時程追蹤)",
    wizDiagQualityTitle: "Quality (資料品質)",
    wizDiagHighlightTitle: "Highlight (風險與支援)",
    wizDiagScheduleGood: "所有活躍專案均準時推進，表現優異！",
    wizDiagScheduleBad: "以下專案進度落後或發生超時：",
    wizDiagQualityGood: "所有專案皆具備具體交付物與進度說明，資料品質優良！",
    wizDiagQualityBad: "以下專案缺乏具體進度或交付物說明，請盡速更新：",
    wizDiagHighlightGood: "目前未偵測到異常風險或跨部門支援需求。",
    wizDiagHighlightBad: "需注意！以下專案標示了風險、異常或支援需求："
  }
};

export const INITIAL_SAMPLE_ROWS = [
  {
    "Owner": "Philip Chang",
    "Status": "Processing",
    "Category": "Architecture",
    "Cluster": "Platform Infrastructure",
    "Due Date": "2026-09-30",
    "Revision_1": "2026-09-30",
    "Duration": 20,
    "Deviation": 0,
    "MH/d": 1.5,
    "Progress": "Phase 2 Core API and Migration in progress (80%)",
    "P.J Description": "MCU-Driven CDU strategy and cloud infrastructure modernization",
    "Highlight & Deliverables": "• Architecture spec v2.1\n• High-throughput caching prototype\n• Security audit clearance"
  },
  {
    "Owner": "Philip Chang",
    "Status": "Processing",
    "Category": "Optimization",
    "Cluster": "Data Pipeline",
    "Due Date": "2026-09-25",
    "Revision_1": "2026-09-25",
    "Duration": 14,
    "Deviation": 0,
    "MH/d": 1.2,
    "Progress": "ETL ingestion optimization pipeline live in staging",
    "P.J Description": "Automated Batch Data Pipeline with Event Streaming",
    "Highlight & Deliverables": "• Reduced data latency by 45%\n• Integration test suite\n• Deployment playbook"
  },
  {
    "Owner": "Alex Chen",
    "Status": "Closed",
    "Category": "UI/UX",
    "Cluster": "Product Design",
    "Due Date": "2026-08-15",
    "Revision_1": "2026-08-15",
    "Duration": 10,
    "Deviation": 0,
    "MH/d": 2.0,
    "Progress": "Completed",
    "P.J Description": "Enterprise Design System V2 and Component Library",
    "Highlight & Deliverables": "• 45 reusable React components\n• Figma design tokens\n• Accessibility compliance audit"
  },
  {
    "Owner": "Alex Chen",
    "Status": "Processing",
    "Category": "UI/UX",
    "Cluster": "Product Design",
    "Due Date": "2026-10-10",
    "Revision_1": "2026-10-10",
    "Duration": 15,
    "Deviation": 0,
    "MH/d": 1.0,
    "Progress": "Wireframing and user testing interviews",
    "P.J Description": "Interactive Gantt & Schedule View Redesign",
    "Highlight & Deliverables": "• Usability report with 12 stakeholders\n• Interactive high-fidelity prototype"
  },
  {
    "Owner": "Sarah Lin",
    "Status": "Closed",
    "Category": "Quality",
    "Cluster": "Platform Infrastructure",
    "Due Date": "2026-07-20",
    "Revision_1": "2026-07-20",
    "Duration": 12,
    "Deviation": 0,
    "MH/d": 1.8,
    "Progress": "Completed",
    "P.J Description": "End-to-End Test Automation Framework Setup",
    "Highlight & Deliverables": "• Cypress + Playwright CI workflows\n• 94% core path coverage"
  },
  {
    "Owner": "Sarah Lin",
    "Status": "Pending",
    "Category": "Quality",
    "Cluster": "Platform Infrastructure",
    "Due Date": "2026-09-12",
    "Revision_1": "2026-09-20",
    "Duration": 8,
    "Deviation": -8,
    "MH/d": 1.5,
    "Progress": "Blocked pending cross-department security review",
    "P.J Description": "Automated Penetration Testing & Vulnerability Assessment",
    "Highlight & Deliverables": "• Risk: Waiting for network team access clearance\n• Initial OWASP scan report"
  },
  {
    "Owner": "David Wang",
    "Status": "Processing",
    "Category": "Analytics",
    "Cluster": "Data Pipeline",
    "Due Date": "2026-10-05",
    "Revision_1": "2026-10-05",
    "Duration": 18,
    "Deviation": 0,
    "MH/d": 2.2,
    "Progress": "Model training and evaluation metrics tuning",
    "P.J Description": "Predictive Workload & Capacity Forecasting Engine",
    "Highlight & Deliverables": "• Forecast accuracy reached 91%\n• REST inference endpoint\n• Documentation"
  },
  {
    "Owner": "David Wang",
    "Status": "Closed",
    "Category": "Analytics",
    "Cluster": "Data Pipeline",
    "Due Date": "2026-08-30",
    "Revision_1": "2026-08-30",
    "Duration": 7,
    "Deviation": 0,
    "MH/d": 2.5,
    "Progress": "Completed",
    "P.J Description": "Real-time Metrics Dashboard & KPI Aggregator",
    "Highlight & Deliverables": "• Real-time websocket feed\n• Executive reporting views"
  },
  {
    "Owner": "Emily Wu",
    "Status": "Processing",
    "Category": "Architecture",
    "Cluster": "Cloud Services",
    "Due Date": "2026-09-28",
    "Revision_1": "2026-09-28",
    "Duration": 14,
    "Deviation": 0,
    "MH/d": 1.6,
    "Progress": "Multi-region failover cluster configuration",
    "P.J Description": "High Availability Cluster & Disaster Recovery Plan",
    "Highlight & Deliverables": "• RTO < 5 minutes target achieved\n• Automated failover scripts"
  },
  {
    "Owner": "Emily Wu",
    "Status": "Closed",
    "Category": "Architecture",
    "Cluster": "Cloud Services",
    "Due Date": "2026-06-30",
    "Revision_1": "2026-06-30",
    "Duration": 10,
    "Deviation": 0,
    "MH/d": 2.0,
    "Progress": "Completed",
    "P.J Description": "Kubernetes Cluster Auto-scaler Tuning",
    "Highlight & Deliverables": "• Cost savings of 28% in cloud compute\n• Grafana dashboards"
  }
];
